### ISSUE TITLE
Warning about pyopencl dependency

### ISSUE THREAD

**Issue by Fivefold** [ChsHub/SSIM-PIL#2]
I use this module for calculating SSIM on a [Zedboard](http://zedboard.org/product/zedboard), which has an ARM CPU and an integrated FPGA.

While the calculation works fine, I get this warning printed in the console: 
```
No module named 'pyopencl'. cl12 version by Christoph Gohlke for windows is recommended: https://www.lfd.uci.edu/~gohlke/pythonlibs/#pyopencl
```
As far as I can see this module (SSIM-PIL) does not list pyopencl as a dependency. In any case, pip did not install it. I actually need that, since pyopencl is a large module of several hundred MB and the Zedboard is both storage-constrained as well as needing to build most wheels itself, which doesn't always work out.

Is there a way to turn off the warning without having to change the source code to remove the try-except block in \_\_main__.py and building the module myself?

Edit: possible but ugly workaround: Use [this code](https://stackoverflow.com/a/45669280/14554676) from StackOverflow to block printing of `compare_ssim`

**Comment by ChsHub** [comment]
If you're using the newest version, you only need to pass `GPU=False` when calling `compare_ssim()`. Then the warning should disappear and it's using the SSIM implementation that doesn't require pyopencl.

**Comment by Fivefold** [comment]
Thank you, this works!
